services:
  - type: web
    name: fillnecode-songlist
    env: docker
    region: Singapore
    plan: free
    
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: vtbdb
          property: connectionString

databases:
  - name: vtbdb
    databaseName: snglstdb
    user: manage_user
    plan: free
    region: Singapore
    ipAllowList: [] # すべてのIPを許可
